name: daily-youtube-stats

on:
  schedule:
    # รันทุกวัน 00:00 เวลาไทย (Bangkok) = 17:00 UTC ของวันก่อนหน้า
    - cron: "0 17 * * *"
  workflow_dispatch:

# ให้สิทธิ์บอทเขียนไฟล์กลับเข้า repo (ใช้ตอน commit CSV)
permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fetcher
        env:
          YT_API_KEY: ${{ secrets.YT_API_KEY }}
        run: |
          python fetch_youtube_stats.py

      - name: Compute milestones
        run: |
          python compute_milestones.py

      - name: Commit & push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/daily_stats.csv data/milestones.csv
          git commit -m "chore: update stats & milestones $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes"
          git push

on:
  schedule:
    - cron: "0 17 * * *"  # 00:00 เวลาไทย
  workflow_dispatch:
  push:
    branches: ["main"]


